[package]
name = "muff"
description = "Multiple USB File Flasher"
version = "0.1.0"
license = "MIT"
authors = ["Jeremy Soller <jeremy@system76.com>"]

[dependencies]
"clap" = "2.26"
"libc" = "0.2"
"pbr" = "1.0"
