[package]
name = "popsicle"
description = "USB Flasher"
version = "0.1.5"
authors = ["Jeremy Soller <jeremy@system76.com>"]
license = "MIT"
readme = "README.md"

[lib]
name = "popsicle"
path = "src/lib.rs"

[workspace]
members = ["cli", "gtk"]

[dependencies]
"libc" = "0.2"
failure = "0.1.1"
failure_derive = "0.1.1"
