[package]
name = "popsicle"
description = "USB Flasher"
version = "0.1.5"
authors = [
    "Jeremy Soller <jeremy@system76.com>",
    "Michael Aaron Murphy <michael@system76.com>",
]
license = "MIT"
readme = "README.md"
edition = "2018"

[lib]
name = "popsicle"
path = "src/lib.rs"

[workspace]
members = ["cli", "gtk"]

[dependencies]
libc = "0.2"
failure = "0.1.1"
failure_derive = "0.1.1"
mnt = "0.3.1"
