[package]
name = "muff_cli"
description = "Multiple USB File Flasher"
version = "0.1.5"
authors = ["Jeremy Soller <jeremy@system76.com>"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "muff"
path = "src/main.rs"

[dependencies]
clap = "2.27.0"
failure = "0.1.1"
failure_derive = "0.1.1"
libc = "0.2"
muff = { path = ".." }
pbr = "1.0.0"
