[package]
name = "muff_gtk"
description = "Multiple USB File Flasher"
version = "0.1.5"
authors = ["Jeremy Soller <jeremy@system76.com>"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "muff-gtk"
path = "src/main.rs"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
gtk = "0.3.0"
libc = "0.2"
muff = { path = ".." }
