[package]
name = "popsicle_gtk"
description = "USB Flasher"
version = "0.2.0"
authors = [ "Michael Aaron Murphy <michael@system76.com>" ]
license = "MIT"
readme = "README.md"

[[bin]]
name = "popsicle-gtk"
path = "src/main.rs"

[dependencies]
atomic = "0.4.3"
bus_writer = "0.1.2"
cascade = "0.1.2"
crossbeam-channel = "0.1"
digest = "0.7.2"
failure = "0.1.1"
failure_derive = "0.1.1"
gdk = "0.9.0"
glib = "0.6.0"
gtk = { version = "0.5.0", features = ["v3_22"] }
hex-view = "0.1"
humansize = "1.1.0"
libc = "0.2"
md-5 = "0.7.0"
pango = "0.5.0"
parking_lot = "0.6.3"
popsicle = { path = ".." }
pwd = "1.2"
sha2 = "0.7.0"
sysfs-class = "0.1.1"
sys-mount = "1.1.0"
proc-mounts = "0.1.2"
