[package]
name = "popsicle_gtk"
description = "USB Flasher"
version = "0.1.5"
authors = [ "Michael Aaron Murphy <michael@system76.com>" ]
license = "MIT"
readme = "README.md"

[[bin]]
name = "popsicle-gtk"
path = "src/main.rs"

[dependencies]
bus_writer = "0.1.1"
failure = "0.1.1"
failure_derive = "0.1.1"
gdk = "0.7.0"
gtk = { version = "0.3.0", features = ["v3_22"] }
libc = "0.2"
popsicle = { path = ".." }
pango = "0.3.0"
pwd = "1.2"
sha2 = "0.7.0"
digest = "0.7.2"
md-5 = "0.7.0"
hex-view = "0.1"
